// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonDetails.WebAPi.DataAccessLayer;

#nullable disable

namespace PersonDetails.WebAPi.Migrations
{
    [DbContext(typeof(PersonDetailDBContext))]
    partial class PersonDetailDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonDetails.WebAPi.Model.PersonDetail", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FromFloor")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ToFloor")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Weight")
                        .HasColumnType("tinyint");

                    b.HasKey("PersonId");

                    b.ToTable("PersonDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
